# Generated by Django 5.2 on 2025-05-09 09:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('study_room', '0002_alter_department_options_alter_studyroom_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='日期')),
                ('total_reservations', models.IntegerField(default=0, verbose_name='总预约数')),
                ('total_hours', models.IntegerField(default=0, verbose_name='总使用小时数')),
                ('usage_rate', models.FloatField(default=0, verbose_name='使用率')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='study_room.studyroom', verbose_name='自习室')),
            ],
            options={
                'verbose_name': '每日统计',
                'verbose_name_plural': '每日统计',
                'ordering': ['-date'],
                'unique_together': {('room', 'date')},
            },
        ),
        migrations.CreateModel(
            name='HourlyStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='日期')),
                ('hour', models.IntegerField(verbose_name='小时(0-23)')),
                ('occupied_seats', models.IntegerField(default=0, verbose_name='占用座位数')),
                ('usage_rate', models.FloatField(default=0, verbose_name='使用率')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='study_room.studyroom', verbose_name='自习室')),
            ],
            options={
                'verbose_name': '每小时统计',
                'verbose_name_plural': '每小时统计',
                'ordering': ['-date', 'hour'],
                'unique_together': {('room', 'date', 'hour')},
            },
        ),
    ]
