# Generated by Django 5.2 on 2025-05-09 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('study_room', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='department',
            options={'verbose_name': '院系', 'verbose_name_plural': '院系'},
        ),
        migrations.AlterModelOptions(
            name='studyroom',
            options={'verbose_name': '自习室', 'verbose_name_plural': '自习室'},
        ),
    ]
