# Generated by Django 5.2 on 2025-05-09 08:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('seat', '0001_initial'),
        ('study_room', '0002_alter_department_options_alter_studyroom_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='日期')),
                ('start_time', models.TimeField(verbose_name='开始时间')),
                ('end_time', models.TimeField(verbose_name='结束时间')),
                ('status', models.CharField(choices=[('waiting', '待签到'), ('checked_in', '使用中'), ('completed', '已完成'), ('cancelled', '已取消'), ('expired', '已过期')], default='waiting', max_length=20, verbose_name='状态')),
                ('check_in_time', models.DateTimeField(blank=True, null=True, verbose_name='签到时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('check_in_code', models.CharField(blank=True, max_length=20, null=True, verbose_name='签到码')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='study_room.studyroom', verbose_name='自习室')),
                ('seat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seat.seat', verbose_name='座位')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '预约',
                'verbose_name_plural': '预约',
                'ordering': ['-date', '-start_time'],
            },
        ),
    ]
