# Generated by Django 5.2 on 2025-05-08 06:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('study_room', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='座位ID')),
                ('code', models.CharField(max_length=20, verbose_name='座位编号')),
                ('status', models.CharField(choices=[('available', '可用'), ('occupied', '已占用'), ('maintenance', '维护中')], default='available', max_length=20, verbose_name='状态')),
                ('has_socket', models.BooleanField(default=False, verbose_name='有电源')),
                ('row', models.IntegerField(verbose_name='行号')),
                ('column', models.IntegerField(verbose_name='列号')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seats', to='study_room.studyroom', verbose_name='所属自习室')),
            ],
            options={
                'verbose_name': '座位',
                'verbose_name_plural': '座位',
                'unique_together': {('room', 'code')},
            },
        ),
        migrations.CreateModel(
            name='FavoriteSeat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_seat_records', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
                ('seat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seat.seat', verbose_name='座位')),
            ],
            options={
                'verbose_name': '收藏座位',
                'verbose_name_plural': '收藏座位',
                'unique_together': {('user', 'seat')},
            },
        ),
    ]
