# Generated by Django 5.2 on 2025-05-08 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seat', '0001_initial'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='favorite_seats',
            field=models.ManyToManyField(related_name='favorited_by', through='seat.FavoriteSeat', to='seat.seat'),
        ),
    ]
