# Generated by Django 5.2 on 2025-05-09 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_reservation_hours', models.IntegerField(default=4, verbose_name='最大预约小时数')),
                ('advance_reservation_days', models.IntegerField(default=7, verbose_name='提前预约天数')),
                ('check_in_grace_period', models.IntegerField(default=15, verbose_name='签到宽限期（分钟）')),
                ('violation_rules', models.TextField(default='累计3次限制预约1天', verbose_name='违规规则')),
                ('violation_limit', models.IntegerField(default=3, verbose_name='违规次数限制')),
                ('penalty_days', models.IntegerField(default=1, verbose_name='违规惩罚天数')),
            ],
            options={
                'verbose_name': '系统设置',
                'verbose_name_plural': '系统设置',
            },
        ),
    ]
