name: Django Backend CI/CD

# 触发条件
on:
  push:
    branches:
      - main

# 环境变量
env:
  PYTHON_VERSION: "3.12"
  ENV: prod

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Build and push studyspot-backend Docker image
        run: |
          docker build -t polarsnowleopard/studyspot-backend:latest .
          docker push polarsnowleopard/studyspot-backend:latest

  # 部署到线上开发测试环境
  deploy-production:
    name: Deploy to Online Development Test Environment
    runs-on: ubuntu-latest
    needs: build
    if: github.event_name == 'push' && (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master')

    steps:
      - uses: actions/checkout@v3

      - name: Create directory on production server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.PRODUCTION_HOST }}
          username: ${{ secrets.PRODUCTION_USERNAME }}
          key: ${{ secrets.PRODUCTION_SSH_KEY }}
          script: |
            mkdir -p ~/studyspot

      - name: Copy files to production server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.PRODUCTION_HOST }}
          username: ${{ secrets.PRODUCTION_USERNAME }}
          key: ${{ secrets.PRODUCTION_SSH_KEY }}
          source: "docker-compose.yml"
          target: "~/studyspot"
          strip_components: 0

      - name: Deploy to production server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.PRODUCTION_HOST }}
          username: ${{ secrets.PRODUCTION_USERNAME }}
          key: ${{ secrets.PRODUCTION_SSH_KEY }}
          script: |
            cd ~/studyspot
            sudo docker pull polarsnowleopard/studyspot-backend:latest
            sudo docker-compose down || true
            sudo docker-compose up -d